apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 3
  selector:
    matchLabels:
      role: project
  template:
    metadata:
      labels:
        role: project
    spec:
      containers:
      - name: project
        image: jrodriguezarc/project
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2
  ports:
  - port: 8080
    targetPort: 80
  selector:
    role: project
